# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#ajbwdjawbdiawbdiuawdbaowdbawuid

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 700)
        MainWindow.setStyleSheet("")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(440, 210, 431, 311))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: Bold 36pt \"Times New Roman\";\n"
"color:#000000;\n"
"font-variant: small-caps;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(900, 0, 461, 701))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 100, 151, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#000000;\n"
"font: 32pt \"Arial\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 250, 111, 21))
        self.label_2.setStyleSheet("color:black;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"letter-spacing:1px;")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(120, 280, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{border-style:solid;\n"
"border-width:1px;\n"
"border-color:#ef17ff;\n"
"border-radius:7px;}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 390, 111, 21))
        self.label_3.setStyleSheet("color:#000000;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"letter-spacing:1px;")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 420, 251, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit{border-style:solid;\n"
"border-width:1px;\n"
"border-color:#ef17ff;\n"
"border-radius:7px;}")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.loginBtn = QtWidgets.QPushButton(self.frame)
        self.loginBtn.setEnabled(True)
        self.loginBtn.setGeometry(QtCore.QRect(190, 550, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setStyleSheet("QPushButton{\n"
"color:#ffffff;\n"
"background-color:#d05bd9;\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"background-color:#b000bd;}\n"
"")
        self.loginBtn.setObjectName("loginBtn")
        self.line = QtWidgets.QFrame(MainWindow)
        self.line.setGeometry(QtCore.QRect(380, 190, 16, 301))
        self.line.setStyleSheet("color:black;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1401, 701))
        self.label_5.setText("")
        self.pxp = QPixmap('warehouse-6-blog.jpg')

        self.label_5.setPixmap(QtGui.QPixmap(self.pxp))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.label_4.setText(_translate("MainWindow", "Inventory Management System"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" \">Login</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Username</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Password</p></body></html>"))
        self.loginBtn.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
